# Site Settings
title: Jekyll
email: psauerbeck@gmail.com
description: >
  Website for Tara McHenry Acupuncture
baseurl: ""
url: "http://localhost:4000"
twitter_username: drink_totemtea
github_username:  pmsaue0
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM