# Site Settings
title: Tara McHenry Acupuncture
email: psauerbeck@gmail.com
description: >
  Website for Tara McHenry Acupuncture
baseurl: "/tara-mchenry-acupuncture"
url: "http://pmsaue0.github.io"
twitter_username: drink_totemtea
github_username:  pmsaue0
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM