# Site Settings
title: Jekyll
email: adamjgomez@gmail.com
description: >
  Adam J Gomez Personal Site
baseurl: ""
url: "http://localhost:4000"
twitter_username: adamjgomez
github_username:  adamjgomez
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM